### PR TITLE
adding iterator to the Card class

### PR DESCRIPTION
**Pull request by lmccartney**
This pull request adds an iter() method to go along with the all() method on the Card class. This should allow users who need to interact with all cards to do so in a more efficient manner.

### CODE REVIEW

**Comment by lmccartney** [comment]
the Card.all() method is not covered by the testing suite, but because Card.all() instanciates _all_ cards into a list, it's not a very practical method to test. Also, it's effectively a wrapper around the iter() method so it not being tested seems acceptable.

**Comment by lmccartney** [comment]
FWIW, just wrote a test to test .all() and it took 18 minutes to complete locally.

**Comment by adback03** [comment]
Sorry for the delay, I should have time to look at this in the next couple days!

**Comment by lmccartney** [comment]
Any update here?

If there is room, I'd be interested in helping maintain this code base.

**Pull request merged**
